
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  chat-server:
    build: .
    environment:
      - KAFKA_BROKER=host.docker.internal:9092   # 도커 내부에서 호스트 Kafka 접근
      - KAFKA_TOPIC=chat-topic
      - KAFKA_GROUP=chat-group
    depends_on:
      - kafka
    ports:
      - "50051:50051"  # localhost:50051 포트 매핑 
    deploy:
      replicas: 2   # 컨슈머(서버) 인스턴스 2개 띄우기
