
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest # KRaft 모드: 주키퍼 필요없음 
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes 
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092  #외부(호스트) 접근도 필요하면 localhost 추가하기 
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka/data


  chat-server:
    build: .
    environment:
      - KAFKA_BROKER=kafka:9092   # 외부 컨테이너에서 Kafka 컨테이너 접근
      - KAFKA_TOPIC=chat-topic
      - KAFKA_GROUP=chat-group
    depends_on:
      - kafka
    # ports:
    #   - "50051:50051" 

volumes:
  kafka_data:
